pipeline {
    agent {
        docker {
            image 'node:18'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        USER_IMAGE = 'saifudheenpv/user-service:latest'
        PRODUCT_IMAGE = 'saifudheenpv/product-service:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Saifudheenpv/microservices-devops.git'
            }
        }

        stage('Build User Service') {
            steps {
                dir('user-service') {
                    sh 'npm install'
                    sh 'docker build -t $USER_IMAGE .'
                }
            }
        }

        stage('Build Product Service') {
            steps {
                dir('product-service') {
                    sh 'npm install'
                    sh 'docker build -t $PRODUCT_IMAGE .'
                }
            }
        }

        stage('Push User Service') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $USER_IMAGE'
                }
            }
        }

        stage('Push Product Service') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $PRODUCT_IMAGE'
                }
            }
        }
    }
}
